version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./work:/work
    environment:
      - "SELENIUM_URL=http://selenium:4444/wd/hub"
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:120.0
    restart: always
    environment:
      - "SE_SCREEN_WIDTH=1920"
      - "SE_SCREEN_HEIGHT=1080"
      - "SE_SCREEN_DEPTH=24"
      - "SE_SCREEN_DPI=96"
    # volumes:
    #   - /dev/shm:/dev/shm
